### CADASTRO

POST http://localhost:3003/users/signup
Content-Type: application/json

{
	"name": "",
	"email": "",
	"password": "",
	"role": ""
}

### LOGIN

###
# @name login

POST http://localhost:3003/users/login
Content-Type: application/json

{
	"email": "",
	"password": ""
}

###

###
@token = {{login.response.body.token}}


### CREATE BAND
POST http://localhost:3003/bands/create
Authorization: {{token}}
Content-Type: application/json

{
    "name": "",
    "music_genre": "",
    "responsible": ""
}

### search band by id or name
GET http://localhost:3003/bands?name=NCS
Authorization: {{token}}

### Register show
POST http://localhost:3003/show/register
Authorization: {{token}}
Content-Type: application/json

{
	"week_day":"", 
	"start_time": , 
    "end_time": ,
    "band_id":""
}

###
GET http://localhost:3003/show/sexta
Authorization: {{token}}


