### CADASTRO

POST http://localhost:3003/users/signup
Content-Type: application/json

{
	"name": "",
	"email": "",
	"password": "",
	"role": ""
}

### LOGIN

###
# @name login

POST http://localhost:3003/users/login
Content-Type: application/json

{
	"email": "macaco@dev.com",
	"password": "querobaanana"
}

###

###
@token = {{login.response.body.token}}


### CREATE BAND
POST http://localhost:3003/bands/create
Authorization: {{token}}
Content-Type: application/json

{
    "name": "NCS",
    "music_genre": "Eletronic",
    "responsible": "Billy Woodford"
}

### search band by id or name
GET http://localhost:3003/bands?name=NCS
Authorization: {{token}}

### Register show
POST http://localhost:3003/show/register
Authorization: {{token}}
Content-Type: application/json

{
	"week_day":"sexta", 
	"start_time": 20, 
    "end_time": 23,
    "band_id":"1a3133e3-93e2-4a8a-8a8b-f9a8b15fa05e"
}

###
GET http://localhost:3003/show/sexta
Authorization: {{token}}


